### ISSUE TITLE
Raw Data for Longitudinal Ancom analysis

### ISSUE THREAD

**Issue by Nicheca** [antagomir/scripts#1]
Hi there, 

The raw data are not longer available at <- read.delim("~/Dropbox/Work at NIEHS/OTU_Ancom_Test_Counts.txt")
I am wondering if you can help me to figure out how the rawdata need to look like for the longitudinal ANCOM analysis? For both the "Mapping_File_ANCOM_Test " & "OTU_Ancom_Test_Counts.txt"

Thank you in advance,

**Comment by antagomir** [comment]
Hi - I am not an ANCOM expert and just tried this once. I propose that you contact the authors of the ANCOM paper?
